### ISSUE TITLE
Unable to submit portfolio when first entering data in edit mode

### ISSUE THREAD

**Issue by Charlielancaster** [holistic-web/portfolio-fabricator#14]
When attempting to first submit your portfolio in edit mode (Upon first filling out of the form), `description` isn't a property of the `experience` object and thus errors when looking for the required property `description`.

The typo in question is the `title` property on https://github.com/holistic-web/portfolio-fabricator/blob/master/portfolio-management/portfolio.schema.json#L105

**Comment by michaelfitzhavey** [comment]
@Charlielancaster can you give an example of one of these issues? I ran this successfully without providing anything for the `description` property of any field (no console errors).

**Comment by michaelfitzhavey** [comment]
@Charlielancaster re reading this it seems like the issue is we cannot submit portfolio's with experience added as the `description` field is being labelled as a `title`.

This is a regression I would have introduced swapping all meta `description` fields over to `titles`; I must have got this one by mistake.

Fixing that one line would be awesome!

**Comment by michaelfitzhavey** [comment]
Looks like there is a PR in progress to fix this here: #15
